# model_source can be set to either "local", "hugging-face-cloud", or "hugging-face-local"
MODEL_SOURCE: "local"

GALILEO_URL: "https://console.hp.galileocloud.io/"

# GALILEO_PROXY is used to configure the HTTPS_PROXY environment variable for Galileo when required
GALILEO_PROXY: "http://web-proxy.austin.hp.com:8080"